### PR TITLE
Fix wrong help_block form option for sonata.seo.block.twitter.embed block

### LINKED ISSUE #185: Can't use sonata.seo.block.twitter.embed block
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.11.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.0  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/cache-bundle              2.3.1  This bundle provides caching services
sonata-project/classification-bundle     3.2.0  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.2.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2    Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.3  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.0  Lightweight Exporter library
sonata-project/formatter-bundle          3.1.0  Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2  Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.3.0  Symfony SonataIntlBundle
sonata-project/media-bundle              3.3.0  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.0.0  Symfony SonataNotificationBundle
sonata-project/page-bundle               3.3.0  This bundle provides a Site and Page management through container ...
sonata-project/seo-bundle                2.0.2  Symfony SonataSeoBundle
sonata-project/user-bundle               3.2.0  Symfony SonataUserBundle

```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge     v2.8.16 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.4.2  Symfony SwiftmailerBundle
symfony/symfony            v2.8.16 The Symfony PHP framework

```

#### PHP version

```bash
$ php -v
PHP 5.5.31 (cli) (built: Jan  6 2016 12:57:50)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

```

## Subject
Can't use `sonata.seo.block.twitter.embed` block (exception is thrown).

## Steps to reproduce
Create a new CMS page, add a `sonata.seo.block.twitter.embed` block block to any container.

## Expected results
No errors are raised adding the block to the container.

## Actual results
The block isn't added. Exception thrown: _The option "help_block" does not exist._

### PR DESCRIPTION
**Pull request by gremo**
I am targetting this branch, because this is a bugfix.

Closes #185

## Changelog

```markdown
### Fixed
- Pass the right option for showing form help in twitter embedded block
```

### CODE REVIEW

**Comment by core23** [comment]
Do we need a dependency for this?

**Comment by gremo** [comment]
@core23 what do you mean?

**Comment by core23** [comment]
`sonata_help` is part of the AdminBundle, which is only a dev dependency atm

**Comment by gremo** [comment]
@core23 I see. What do you suggest? Can we simply get rid of `help_block`? I can't ding anything about the option `help_block`.

File: Block/Social/TwitterEmbedTweetBlockService.php [hunk 1]
```diff
@@ -94,27 +94,27 @@ public function buildEditForm(FormMapper $form, BlockInterface $block)
                 array('tweet', 'textarea', array(
                     'required' => true,
                     'label' => 'form.label_tweet',
-                    'help_block' => 'form.help_tweet',
+                    'sonata_help' => 'form.help_tweet',
```
Comment (core23) [inline Block/Social/TwitterEmbedTweetBlockService.php]: Ping @gremo

Comment (gremo) [inline Block/Social/TwitterEmbedTweetBlockService.php]: This would not show the help at all but if it's fine for you it's fine for me, i can change this PR (see https://sonata-project.org/bundles/admin/master/doc/reference/form_help_message.html#help-messages-in-a-sub-field).

Comment (core23) [inline Block/Social/TwitterEmbedTweetBlockService.php]: Can you examine why this wouldn't show? Maybe we should fix this.

Comment (core23) [inline Block/Social/TwitterEmbedTweetBlockService.php]: Ping @gremo

Comment (core23) [inline Block/Social/TwitterEmbedTweetBlockService.php]: Any updates here @gremo ?

**Comment by gremo** [comment]
@core23 I can't, really. I dont' understand the internals of the FormMapper, so I can't help here.

**Comment by gremo** [comment]
@core23 I think we should merge https://github.com/sonata-project/SonataAdminBundle/pull/4655 and stick  with the `sonata_help` option. I can't find any option named `help` and the example in [the documentation](https://sonata-project.org/bundles/admin/master/doc/reference/form_help_message.html#id1) maybe wrong.

**Comment by gremo** [comment]
@Soullivaneuh updated the PR changelog... can you merge?

**Comment by core23** [comment]
We should move the `sonata_help` stuff to the CoreBundle and create a new `HelpExtensionType`. Afterwards, we could rely on the key.

**Comment by gremo** [comment]
@core23 I'm going to close this, as https://github.com/sonata-project/SonataAdminBundle/pull/4655 has been merged and help will work now.

**Comment by greg0ire** [comment]
Thanks @gremo !
